#!/bin/sh

PYWAL()
{
  WAL_VARS()
  {
    COLORLIST=~/.cache/wal/colors
    XRESOURCES=~/.cache/wal/colors.Xresources  
  }
  
  WAL_COLORS()
  {
    COLOR_01=$(sed -n 10,10p $COLORLIST)
    COLOR_02=$(sed -n 1,1p $COLORLIST)
    COLOR_03=$(sed -n 6,6p $COLORLIST)
    COLOR_04=$(sed -n 4,4p $COLORLIST)
  }

  WAL_WRITE()
  {
    echo "!!dmenu" > $XRESOURCES
    echo "dmenu.background:       $COLOR_01" >> $XRESOURCES
    echo "dmenu.foreground:       $COLOR_02" >> $XRESOURCES
    echo "dmenu.selbackground:    $COLOR_03" >> $XRESOURCES
    echo "dmenu.selforeground:    $COLOR_04" >> $XRESOURCES
  }
  
  WAL_SET()
  {
  test /usr/bin/xrdb && test ~/.cache/wal/colors.Xresources || touch ~/.cache/wal/colors.Xresources
  test ~/.cache/wal/colors.Xresources && xrdb -query | grep -q "color66" && printf "Using pywal" > /tmp/dmenurunlog && xrdb -merge ~/.cache/wal/colors.Xresources
  }

  WAL_VARS
  WAL_COLORS
  WAL_WRITE
  WAL_SET
}

PYWAL

dmenu_path | dmenu "$@" | ${SHELL:-"/bin/sh"} &
